version: '3.8'
services:
  setup:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    depends_on:
      - mongodb
    env_file:
      - path: .env
        required: true
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    env_file:
      - path: .env
        required: true